# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    command: gunicorn --bind 0.0.0.0:${PORT_SERVING} app:app
    image: ift6758/serving:${TAG}
    ports:
      - ${PORT_SERVING}:${PORT_SERVING}
    environment:
      - COMET_API_KEY=${COMET_API_KEY}


###### Uncomment below when you're ready to add the final notebook container to your docker compose
##  jupyter:
##    build:
##      context: ./
##      dockerfile: ./Dockerfile.jupyter
##      args:
##        ARG: <ARG>
##    image: ift6758/jupyter:<TAG>
##    ports:
##      - <JUPYTER_PORT>:<JUPYTER_PORT>
##    environment:
##      OTHER_DOCKER_ENV_VAR = ${OTHER_LOCAL_ENV_VAR}