name: ift6758-conda-env
channels:
  - conda-forge
  - comet_ml
dependencies:
  - python>=3.6
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - requests
  - opencv
  - tqdm
  - lxml
  - plotly
  - setuptools
  - ipykernel
  - ipywidgets
  - jupyterlab>=3.0.0
  - ipdb
  - xgboost
  - tensorflow=2.6.0
  - keras=2.6.0
  - comet_ml
