# Setup
title:               IFT6758 Milestone2 Blog
tagline:             'By J.Qasim, L.Marcotte, S.Bahig, J.Plantin'
description:         ''
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              J.Qasim, L.Marcotte, S.Bahig, J.Plantin
  url:               https://github.com/jaihon1/IFT6758-Project
  email:             jaihon.qasim@umontreal.ca, laurence.marcotte@umontreal.ca, sami.bahig@umontreal.ca, johann.plantin@umontreal.ca

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
